### ISSUE TITLE
[개선] 실행 바이너리 파일 (.exe) 빌드 배포 정책

### ISSUE THREAD

**Issue by binchoo** [binchoo/selnium-kakao-vaccine-reservation#31]
## 현재의 불편한 상황
python 사용 경험이 없는 이용자의 경우 앱 사용이 불편할 수 있다.

## 개선 내용 및 방향
윈도우 및 macOS용 실행 바이너리를 빌드하고 배포하는 자동화 절차를 정의하고, 적용시켜 보자.
깃허브 액션즈 사용이 유력하다.

## 배포 정책

1. master에 최종 검수된 소스 코드를 커밋합니다.
2. master -> dist 브랜치로 풀리퀘를 생성합니다.
3. Github Actions가 윈도우와 맥용 바이너리를 생성합니다. dist 브랜치 dist 폴더에 커밋됩니다.
4. 본인은 개인 환경에서 master <- dist를 머지한 다음 push 합니다.
5. 태그를 붙이고 릴리스를 생성합니다.

**Comment by Cjwuc** [comment]
안녕하세요 개발자님 혹시 pip install -r requirements.txt
python qtmain.py
이코드를 파이썬 설치후 cmd창에 입력하면 되는 건가요?

**Comment by binchoo** [comment]
@Cjwuc 네 맞습니다. 어떤 문제가 발생하셨나요?

**Comment by Cjwuc** [comment]
파이썬 설치후 cmd에서 코드 입력후 pip내부 또는 외부명령 실행할수 있는 프로그램이 아니라고 뜨는데 혹시 실행방법이 잘못 됫나요 ㅠㅠㅠ

**Comment by binchoo** [comment]
@Cjwuc 고생 많으십니다.
CMD가 pip 명령어를 찾을 수 없나본데요.
그럴때는
- 직접 `pip.py`가 설치된 위치에서 pip명령어를 입력하거나
- 시스템 환경변수 PATH를 수정하여 `pip.py` 위치를 추가하여야 합니다.

관련 가이드를 참고해 보세요
출처 - https://www.nomadism.co.kr/154

.exe 실행파일을 제공할 수 있도록 연구하고 적용해 보겠습니다. 감사합니다.

**Comment by Cjwuc** [comment]
헐 ㅠㅠㅠ 감사합니다 개발자님 바쁘실텐데  정말 감사합니다

**Comment by binchoo** [comment]
## 배포 정책

1. master에 소스 코드 커밋
2. 커밋에 태그를 붙이고 릴리스
3. dist 브랜치로 풀리퀘 생성
4. actions가 윈도우와 맥용 바이너리를 생성
5. dist 브랜치 /dist 폴더에 커밋해 줌
6. 본인은 해당 바이너리를 다운로드하여 릴리스에 추가해줌.

**Comment by binchoo** [comment]
## 배포 절차 테스트 완료
![image](https://user-images.githubusercontent.com/15683098/128595526-477d6585-9418-4db1-86fa-8c432fa90d18.png)

현재 정책 3단계에 놓여있음.
4단계. master로 dist를 머지하고
5단계. 1.1 태그 붙여서 릴리스 바람.

**Comment by binchoo** [comment]
### 작업 완료
- 깃허브 액션즈로 맥OS와 윈도우용 바이너리를 컴파일 한다. [dist브랜치의 dist 폴더](https://github.com/binchoo/selenium-kakao-vaccine-reservation/tree/dist/dist)에 생성됨.
- dist를 master에 머지한 뒤 태그를 1.1로 붙여서 릴리스 함.
- 따라서 앞으로의 릴리스에는 바이너리 파일이 반드시 포함됩니다.



### 워크플로 야믈 - 윈도우 바이너리 빌드
```yaml
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pyinstaller-window-compile

on:
  push:
    branches: [ dist ]
  pull_request:
    branches: [ dist ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: build exe file
      run: |
        pyinstaller --onefile qtmain.py
    - name: commit and push
      shell: cmd
      run: |
        git config --global user.name 'binchoo'
        git config --global user.email 'jbinchoo@gmail.com'
        git add dist
        git commit -m "Build windows binary."
        git pull
        git push
```
